---
# tasks file for schedServerStatusDeployment
- name: Stop schedServerStatus
  notify:
    - Stop schedServerStatus
  tags: stopService

- name: Start schedServerStatus
  notify:
    - Start schedServerStatus
  tags: startService

- name: Restart schedServerStatus
  notify:
    - Restart schedServerStatus
  tags: reStartService